### ISSUE TITLE
Generate VLess in v2board 

### ISSUE THREAD

**Issue by saeed1024** [therealaleph/xrayr-reality#2]
How to generate vlees in v2board?!

**Comment by therealaleph** [comment]
You may enable VLESS in xrayr's config.yml but you have to change your subscription links in order to show it.

**Comment by REZA-ZAMANIAN** [comment]
> You may enable VLESS in xrayr's config.yml but you have to change your subscription links in order to show it.

By that you mean when you update the subscription link, It won't load any vless and loads vmess only and you should change it manually to vless right?
If that's the case, Don't you have any ideas of how to add vless to the panel and make it part of the sub? Because if it's gonna be done manually, There are other panels that do this better. All the power of this panel comes from that sub link.
Thank you.
